// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_knn_to_sparse_weights
Rcpp::List rcpp_knn_to_sparse_weights(Rcpp::IntegerMatrix& knn_index, Rcpp::NumericMatrix& knn_dist, bool self_loops);
RcppExport SEXP _scArtifact_rcpp_knn_to_sparse_weights(SEXP knn_indexSEXP, SEXP knn_distSEXP, SEXP self_loopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type knn_index(knn_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type knn_dist(knn_distSEXP);
    Rcpp::traits::input_parameter< bool >::type self_loops(self_loopsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_knn_to_sparse_weights(knn_index, knn_dist, self_loops));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_knn_to_sparse_idx
Rcpp::List rcpp_knn_to_sparse_idx(Rcpp::IntegerMatrix& knn_index, bool self_loops);
RcppExport SEXP _scArtifact_rcpp_knn_to_sparse_idx(SEXP knn_indexSEXP, SEXP self_loopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type knn_index(knn_indexSEXP);
    Rcpp::traits::input_parameter< bool >::type self_loops(self_loopsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_knn_to_sparse_idx(knn_index, self_loops));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scArtifact_rcpp_knn_to_sparse_weights", (DL_FUNC) &_scArtifact_rcpp_knn_to_sparse_weights, 3},
    {"_scArtifact_rcpp_knn_to_sparse_idx", (DL_FUNC) &_scArtifact_rcpp_knn_to_sparse_idx, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_scArtifact(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
