// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_get_sparse_dist
Rcpp::List rcpp_get_sparse_dist(Rcpp::IntegerMatrix& knn_index, Rcpp::NumericMatrix& knn_dist, int n_obs, int n_neighbors);
RcppExport SEXP _scArtifact_rcpp_get_sparse_dist(SEXP knn_indexSEXP, SEXP knn_distSEXP, SEXP n_obsSEXP, SEXP n_neighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type knn_index(knn_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type knn_dist(knn_distSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_sparse_dist(knn_index, knn_dist, n_obs, n_neighbors));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scArtifact_rcpp_get_sparse_dist", (DL_FUNC) &_scArtifact_rcpp_get_sparse_dist, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_scArtifact(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
