# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_knn_to_sparse_weights <- function(knn_index, knn_dist, self_loops) {
    .Call('_scArtifact_rcpp_knn_to_sparse_weights', PACKAGE = 'scArtifact', knn_index, knn_dist, self_loops)
}

rcpp_knn_to_sparse_idx <- function(knn_index, self_loops) {
    .Call('_scArtifact_rcpp_knn_to_sparse_idx', PACKAGE = 'scArtifact', knn_index, self_loops)
}

